////["类型","英","中"]
///////[0,1,2]
var lang={
	"web_title":["tp_shopping","Shopping Channel","购物频道"]
	,"language":["tp_slang","Select Language","选择语言"]
	,"search":["tp_sch","Search","收索"]
	,"sch_want":["tp_schwt","Search you want...","收你喜欢..."]
	,"menu":[
				["tp_home","Home","首页"]
				,["tp_dis","Discovery","发现"]
				,["tp_sc","Subscription","订阅"]
				,{"multi":["tp_vc","Vivian Chang","张怡琪"]
					,"sublevel":[
											["tp_fb","Favorite Bloggers","博客"],["tp_bm","Bookmark","书签"]
											,["tp_wl","Wishlist","愿望清单"],["tp_as","Account Settings","帐户设置"]
										]
				}
				,["tp_cart","Shopping Cart","购物车"]
				,["tp_msg","Message","个人信息"]
				,["tp_hst","My History","我的历史"]
	]
	,"page_menu":[
				["/","HOME","首页"]
				,["video","VIDEOS","视频"]
				,["#","PRODUCTS","产品"]
				,["#","ABOUT","关于"]
	]
	,"footer_menu":[
									["tp_au","About Us","关于我们"],["tp_join","Join our Team","加入我们"]
									,["tp_cu","Contact Us","联系我们"],["tp_hc","Help Center","帮助中心"]
									,["tp_ts","Terms","法律声明"],["tp_priv","Privacy","隐私条款"]
								]
	,"copyright":["tp_copyr","© 360 Shopping Channel 2016","© 360 购物频道 2016"]
	,"prev":["prev","Previous","上一页"]
	,"next":["next","Next","下一页"]
	,"views":["views","views","观看"]
	,"hago":["dago","hours ago","小时前"]
	,"dago":["dago","days ago","天前"]
	,"mago":["mago","months ago","月前"]
	,"upload":["Upload","Upload","更新于"]
	,"May":["May","May","5"]
	,"bookmark":["Bookmark","Bookmark Video","书签视频"]
	,"share":["share","Share","分享"]
	,"copyLink":["Copy Link","Copy Link","复制链接"]
	,"addAll":["addAll","Add All to Cart","全部加入"]
	,"add2Cart":["add2Cart","Add To Cart","加入购物车"]
	,"scanQR":["scanQR","Scan the QR code add all products to your shopping cart","扫描二维码添加产品到购物车"]
	,"noStock":["noStock","Sorry, no longer available","对不起，不再提供"]
	,"soldOut":["soldOut","Sold Out!","卖完了"]
	,"showMore":["more","SHOW MORE","更多"]
	,"openMore":["more","Open More","更多"]
	,"follow":["flw","Follow","收藏"]
	,"followers":["flwr","Followers","人收藏"]
	,"comments":["cmt","Comments","评论"]
	,"topCmt":["cmt","TOP COMMENTS","置顶评论"]
	,"newest":["cmt","NEWEST FIRST","最近评论"]
	,"post":["cmt","Post","发送"]
	,"writeCmt":["wcmt","Write your comment...","写你的评论…"]
	,"reply":["Reply","Reply","回复"]
	,"mrReply":["mrReply","Open more replys","更多回复"]
};
module.exports = lang;